apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-crystal
  labels:
    app: helm-crystal
  namespace: default
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: helm-crystal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helm-crystal
    spec:
      containers:
      - image: {{ .Values.crystal.image }}:{{ .Values.version }}
        imagePullPolicy: Always
        name: helm-crystal
        ports:
        - containerPort: 3000
          protocol: TCP
