apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-frontend
  labels:
    app: helm-frontend
  namespace: default
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: helm-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helm-frontend
    spec:
      containers:
      - image: {{ .Values.frontend.image }}:{{ .Values.version }}
        imagePullPolicy: Always
        name: helm-frontend
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: CRYSTAL_URL
          value: "http://helm-crystal.default.svc.cluster.local/crystal"
        - name: NODEJS_URL
          value: "http://helm-nodejs.default.svc.cluster.local/"
